version: '3.8'

services:
  db:
    image: mysql:8.0.29
    env_file: .env
    restart: unless-stopped
    volumes:
      - ./db:/var/lib/mysql:rw
    ports:
      - "3306:3306"

  bot:
    image: maven:3.9.9-eclipse-temurin-21-alpine
    env_file: .env
    depends_on:
      - db
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./bot:/app:rw
      - .m2:/root/.m2:rw
    command: >
      sh -c "mvn clean package -DskipTests &&
             java -jar target/*.jar"
    ports:
      - "8080:8080"