version: '3.8'

services:
  myapp:
    image: openjdk:21
    container_name: bot_app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bot
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./bot:/app
    working_dir: /app
    command: ["sh", "-c", "cd /app && ./mvnw clean package && java -jar target/*.jar"]

  db:
    image: postgres:17-alpine
    container_name: bot_postgres
    environment:
      POSTGRES_DB: bot
      POSTGRES_USER: bot
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data