version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ../.env
    ports:
      - "8080:8080"
    volumes:
      - ./log:/app/log
      - ./db:/app/db
