services:
  bot:
    image: bitsneak/discord-school-bot:latest
    restart: unless-stopped
    env_file: ../.env
    ports:
      - "8080:8080"
    volumes:
      - ./log:/app/log:rw
      - ./db:/app/db:rw
