name: Build Docker Image

on:
  push:
    branches:
      - main
    paths-ignore:
      - .github/**
      - LICENSE
      - CHANGELOG.md
      - CODEOWNERS
      - CODE_OF_CONDUCT.md
      - CONTRIBUTING.md
      - README.md
      - SECURITY.md
  pull_request:
    branches:
      - main
    paths-ignore:
      - .github/**
      - LICENSE
      - CHANGELOG.md
      - CODEOWNERS
      - CODE_OF_CONDUCT.md
      - CONTRIBUTING.md
      - README.md
      - SECURITY.md
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
          context: docker
          push: false
